export interface Project {
  id: number;
  title: string;
  location: string;
  type: "Residential" | "Commercial" | "Industrial" | "Resi.+Commercial" | "Resi./Comm./Rowhouse";
  image: string; // Keep for backward compatibility/thumbnail
  images: string[]; // New array for carousel
  startDate: string;
  endDate: string;
  durationMonths: number;
  highlights: string[];
  description: string;
  area: string;
  status: "Completed" | "In Progress" | "Upcoming";
  lat?: number;
  lon?: number;
  year?: string;
}

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "Shelter CHS",
    location: "Shraddhanand Road, Vile Parle (E), Mumbai",
    type: "Resi.+Commercial",
    image: "/images/projects/tech-park.jpg",
    images: ["/images/projects/shelter/shelter-1.jpeg", "/images/projects/shelter/shelter-2.jpeg"],
    startDate: "IOD",
    endDate: "---",
    durationMonths: 0,
    highlights: [
      "Commercial development",
      "Luxury living",
      "Prime location",
      
    ],
    description:
      "Thoughtfully designed compact residences with seamless commercial integration, offering a complete ecosystem of modern amenities.",
    area: "15,000 sq ft",
    status: "Upcoming",
    lat: 19.09310813701736,
    lon: 72.84631502269733,
    year: "-",
  },
  {
    id: 2,
    title: "Saideep Apartment",
    location: "Rajasthan Society, J.B Nagar, Andheri (E), Mumbai",
    type: "Residential",
    image: "/images/projects/gold-residences.jpg",
    images: ["/images/projects/saideep/saideep-1r.jpeg", "/images/projects/saideep/saideep-2r.jpeg", "/images/projects/saideep/saideep-3r.jpg", "/images/projects/saideep/saideep-4r.jpg", "/images/projects/saideep/saideep-5r.jpg", "/images/projects/saideep/saideep-6r.jpg", "/images/projects/saideep/saideep-7r.jpg", "/images/projects/saideep/saideep-8r.jpg", "/images/projects/saideep/saideep-9r.jpg", "/images/projects/saideep/saideep-10r.jpg", "/images/projects/saideep/saideep-11r.jpg", "/images/projects/saideep/saideep-12r.jpg", "/images/projects/saideep/saideep-13r.jpg", "/images/projects/saideep/saideep-14r.jpg", "/images/projects/saideep/saideep-15r.jpg", "/images/projects/saideep/saideep-16r.jpg"],
    startDate: "Jun 2022",
    endDate: "Jun 2024",
    durationMonths: 24,
    highlights: [
      "20+ luxury apartments",
      "5-star amenities",
      "Premium parking",
      "Smart home automation",
    ],
    description:
      "A premium residential development redefining luxury living in Andheri with eco-conscious design and world-class amenities.",
    area: "25,000 sq ft",
    status: "Completed",
    lat: 19.11024717154869,
    lon: 72.8695991008313,
    year: "2024",
  },
  {
    id: 3,
    title: "Vijay Apartment",
    location: "M.G. Cross Road No. 2, Kandiwali (W), Mumbai",
    type: "Residential",
    image: "/images/projects/archcon-towers.jpg",
    images: ["/images/projects/vijay/1.png", "/images/projects/vijay/vijay-2.png", "/images/projects/vijay/vijay-3.png", "/images/projects/vijay/vijay-4.png"],
    startDate: "Dec 2016",
    endDate: "Nov 2018",
    durationMonths: 23,
    highlights: [
      "Premium construction",
      "12-storey building",
      "Premium parking",
    ],
    description:
      "Modern residences with vastu-compliant design, thoughtfully planned layouts, and a seamless automated puzzle parking system.",
    area: "28,500 sq ft",
    status: "Completed",
    lat: 19.204512896893068,
    lon: 72.8439046695957,
    year: "2018",
  },
  {
    id: 4,
    title: "Krish Royale",
    location: "Shimpoli Road, Borivali (W), Mumbai",
    type: "Residential",
    image: "",
    images: ["/images/projects/krish/11.png", "/images/projects/krish/2.png", "/images/projects/krish/3.png"],
    startDate: "April 2010",
    endDate: "Dec 2012",
    durationMonths: 33,
    highlights: [
      "Calm Location",
      "Premium construction",
      "Good connectivity",
    ],
    description:
      "Contemporary residential community designed for the modern professional, combining comfort, connectivity, and sustainable living.",
    area: "18,000 sq ft",
    status: "Completed",
    lat: 19.22137813840749,
    lon: 72.84599410987323,
    year: "2013",
  },
  {
    id: 5,
    title: "Vastubh Apartment",
    location: "Dattapada, Borivali (E), Mumbai",
    type: "Residential",
    image: "",
    images: ["/images/projects/vastubh/11.png","/images/projects/vastubh/2.png"],
    startDate: "Mar 2005",
    endDate: "Dec 2006",
    durationMonths: 24,
    highlights: [
      "Sustainable design",
      "Office spaces",
    ],
    description:
      "Innovative development blending commercial and residential spaces, creating vibrant, well-integrated urban environments for modern living.",
    area: "7,000 sq ft",
    status: "Completed",
    lat: 19.222972112820834,
    lon: 72.85639335819292,
    year: "2007",
  },
  {
    id: 6,
    title: "Bhailal Steel Impex",
    location: "Kashimira, Mira Road, Mumbai",
    type: "Industrial",
    image: "",
    images: [""],
    startDate: "Apr 2002",
    endDate: "Feb 2004",
    durationMonths: 22,
    highlights: [
      "Premium units",
      "Logistics facility",
      "Co-working spaces",
    ],
    description:
      "Strategic industrial complex with cutting-edge logistics infrastructure, optimizing supply chain efficiency for India's growing economy.",
    area: "22,000 sq ft",
    status: "Completed",
    lat: 19.27208114776594,
    lon: 72.8840193495014,
    year: "2004",
  },
  {
    id: 7,
    title: "Parikh Industrial Estate",
    location: "Kashimira, Mira Road, Mumbai",
    type: "Industrial",
    image: "",
    images: [""],
    startDate: "Jan 2000",
    endDate: "Dec 2002",
    durationMonths: 36,
    highlights: [
      "IT hub development",
      "Innovation center",
      "High-speed connectivity",
      "Startup ecosystem",
    ],
    description:
      "A world-class technology park fostering innovation and entrepreneurship with state-of-the-art facilities for next-generation businesses.",
    area: "35,000 sq ft",
    status: "Completed",
    lat: 19.270566565741046,
    lon: 72.8819504183833,
    year: "2002",
  },
  {
    id: 8,
    title: "Hatkesh Udyog Nagar (12 Buildings)",
    location: "Hatkesh, Mira-Bhayandar Road, Mira Road, Mumbai",
    type: "Industrial",
    image: "",
    images: [""],
    startDate: "April 1998",
    endDate: "March 2004",
    durationMonths: 72,
    highlights: ["Architectural design", "Consulting Work"],
    description:
      "A high-end industrial development engineered to redefine industrial ecosystems through precision, scale, and innovation.",
    area: "2,50,000 sq ft",
    status: "Completed",
    lat: 19.28140709396304,
    lon: 72.87885187018514,
    year: "2004",
  },
  {
    id: 9,
    title: "Patel Precision Engineering Pvt. Ltd.",
    location: "Nehroli, Wada",
    type: "Industrial",
    image: "",
    images: [""],
    startDate: "Apr 1998",
    endDate: "Dec 1999",
    durationMonths: 21,
    highlights: ["Industrial Shed", "Office building"],
    description:
      "Modern commercial and industrial hub with premium offices, retail, and industrial sheds for forward-thinking enterprises",
    area: "20,000 sq ft",
    status: "Completed",
    lat: 19.59686778047216,
    lon: 73.11860314406887,
    year: "1999",
  },
  {
    id: 10,
    title: "Al-Pack Paper Packaging Pvt. Ltd.",
    location: "Nehroli, Wada",
    type: "Industrial",
    image: "",
    images: [""],
    startDate: "Feb 1997",
    endDate: "Dec 1998",
    durationMonths: 23,
    highlights: [
      "Logistics facility",
      "Smart warehousing",
      "Rail connectivity",
      "ISO compliant",
    ],
    description:
      "Strategic industrial building with cutting-edge logistics infrastructure, optimizing supply chain.",
    area: "30,000 sq ft",
    status: "Completed",
    lat: 19.597890010662127,
    lon: 73.11898960756184,
    year: "1998",
  },
  {
    id: 11,
    title: "Kohinoor Apartment",
    location: "Satellite Park, Mira Road (E), Mumbai",
    type: "Resi.+Commercial",
    image: "",
    images: [""],
    startDate: "Feb 1999",
    endDate: "Jan 2002",
    durationMonths: 35,
    highlights: [
      "Sustainable design",
      "Vastu compliant",
    ],
    description:
      "An innovative community-centric development blending commerce with nature, creating vibrant urban spaces for modern living.",
    area: "12,000 sq ft",
    status: "Completed",
    lat: 19.284740216460868,
    lon: 72.87973961535695,
    year: "2002",
  },
  {
    id: 12,
    title: "Glory Apartment",
    location: "Satellite Park, Mira Road (E), Mumbai",
    type: "Residential",
    image: "",
    images: [""],
    startDate: "Dec 1998",
    endDate: "Dec 2000",
    durationMonths: 24,
    highlights: [
      "40+ premium units",
    ],
    description:
      "Contemporary residential community designed for the modern professional, combining comfort, connectivity, and sustainable living.",
    area: "8,000 sq ft",
    status: "Completed",
    lat: 19.285594463513803,
    lon: 72.88039072728012,
    year: "2000",
  },
  {
    id: 13,
    title: "Satellite Park",
    location: "Hatkesh, Mira Road (E), Mumbai",
    type: "Resi./Comm./Rowhouse",
    image: "",
    images: [""],
    startDate: "Jan 2023",
    endDate: "Aug 2025",
    durationMonths: 31,
    highlights: [
      "Comman garden",
      "Club House",
    ],
    description:
      "A world-class residential complex with state-of-the-art facilities.",
    area: "1,50,000 sq ft",
    status: "Completed",
    lat: 19.28511054504845,
    lon: 72.880150289423,
    year: "2000",
  },
  {
    id: 14,
    title: "Dev-Ashish",
    location: "Shirdi Nagar, Bhayandar (E), Thane",
    type: "Residential",
    image: "",
    images: [""],
    startDate: "Mar 1987",
    endDate: "Dec 1989",
    durationMonths: 33,
    highlights: [
      "20+ premium units",
    ],
    description:
      "A residential building crafted for professionals, blending comfort, seamless connectivity, and sustainable living.",
    area: "10,000 sq ft",
    status: "Completed",
    lat: 19.305541741218736,
    lon: 72.86219516590693,
    year: "1989",
  },
];
